### ISSUE TITLE
Export Starship to PDF

### ISSUE THREAD

**Issue by speed-of-heat** [bcholmes/StarTrek2d20#1]
Using edge seem to create an error, no pdf is generated

"Hmmm… can't reach this pageCheck if there is a typo in pdf.modiphiusapps.hostinguk.org.
Search the web for pdf modiphiusapps hostinguk org
If spelling is correct, try running Windows Network Diagnostics."

**Comment by bcholmes** [comment]
Thanks for the bug report and for providing such specific information! 

Basically the root problem is that the original code sent all the character creation data to the modiphiusapps server to render the PDF. I've re-written this code for normal and supporting characters (to support additional types of sheets), but the starship sheets are still constructed the old way. And the modiphiusapps site has been down recently. I've already started working on a fix, and will have something very soon.

**Comment by speed-of-heat** [comment]
Thanks for the quick response, cool tool btw!

**Comment by bcholmes** [comment]
I've deployed v1.210922 (see bottom right-hand corner of the screen), which should fix this problem. Like all quickly-implemented things, there's a chance I've missed something, so I'll keep my eye on testing over the next few days.

**Comment by speed-of-heat** [comment]
yep that seems to work !  thanks !
