### ISSUE TITLE
Starships: Cheyenne-class is missing

### ISSUE THREAD

**Issue by TakeshiYamato01** [bcholmes/StarTrek2d20#109]
So, yeah. as the title says, I'm not seeing the Cheyenne-class in the stock spaceframes on the Starfleet side, and it is in the Utopia Planitia book, just before its cousin, the Springfield-class.

**Comment by bcholmes** [comment]
Yup, that's missing all right.

**Comment by TakeshiYamato01** [comment]
In there now. Nice. :)
