### ISSUE TITLE
Suggestion: Include mission pod as trait

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#113]
As the ship character sheets don't have a space to note the mission pod (other than writing it next to or asterisking the talents), I think that it should be added to the traits (or potentially the mission profile?).

**Comment by bcholmes** [comment]
I took a slightly different take on this. I've added the "Mission Pod" special rule, and when that appears in the Special Rules section of the sheet, I spell out the mission pod there.
