### ISSUE TITLE
Brak'lul not available as cross-species talent?

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#123]
I was looking at #42 and noticed that Brak'lul is not visible to characters even with "allow cross-species talents" selected unless they are Klingon (non QuchHa’), or mixed species and have Klingon as one of their species. Brak'lul should be available to QuchHa’ Klingons regardless, and should be available generally if the cross-species selection is allowed.

A QuchHa’ "receives full access to all the Klingon-specific talents detailed on page 119" (KDF pg 98-99) which includes Brak'lul.

**Comment by bcholmes** [comment]
I've updated the code to allow the Brak'lul to be selected by QuchHa'. The original code base has a notion of "talents that are allowed by cross-species" and "talents that are no allowed by cross-species". I'm not sure why; I'll have to dig in to that.

**Comment by Felderburg** [comment]
I thought something like that might be the case when I looked at the code, but didn't actually dig in. In the books, some talents are "Species, or GM Permission," whereas other talents are just "Species" (e.g. Orion talents vs. VinShari in the Shackleton book). So that's probably why... I suppose the question would be whether it makes sense to maintain that distinction in a tool used by GMs who may be especially permissive (or perhaps add another checkbox, so it's 'allow cross-species' and 'allow all').

**Comment by bcholmes** [comment]
> The original code base has a notion of "talents that are allowed by cross-species" and "talents that are no allowed by cross-species". I'm not sure why; I'll have to dig in to that.

I think this boils down to whether or not the species talent says "or GM's permission". According to the Klingon Rule Book, Brak'lul is not a "or GM's permission" talent whereas "Killer's instinct", "R'uustai", "To Battle!" and "Warrior's Spirit" are.
