### ISSUE TITLE
Proposal: Allow individual star systems to be exported

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#132]
The individual star system portion of the sector generator includes some very cool images, that aren't currently exported with the whole sector. Additionally, it may be useful for people who don't want a multi-page pdf and only want to export specific systems, after viewing them in the tool.

**Comment by Felderburg** [comment]
Very cool!

What is the reason the system diagram isn't also in the pdf?

**Comment by bcholmes** [comment]
Only that it requires a bit of work. Drawing the diagram on a PDF and drawing it on a screen require different code approaches (and I think there are a few limitations with the PDF approach that I'm gonna hafta accept -- things like not being able to use the gradients to make the stars and worlds look a nice as they do on the screen). 

It's still part of the plan to get that implemented; I just need time to get there.

**Comment by Felderburg** [comment]
I was curious, and assumed there was some sort of code limitation. I still have no idea how exporting anything to pdf works.

**Comment by Felderburg** [comment]
Well this is closed as far as I'm concerned. I did notice that in one exported system, because there were several worlds in close proximity to the star, the width of the LCARS AU/distance bar was too small for one of the worlds, so its distance was not written in that bar. But it was still contained in the listing for the world, so it's not a big deal.

But the whole thing is very cool, nicely done!
