### ISSUE TITLE
Can't view the normal upbringing options after viewing the alternate list

### ISSUE THREAD

**Issue by butterdroid** [bcholmes/StarTrek2d20#136]
**Actual**
Can't view the normal upbringing options after viewing the alternate list

**Expected**
Should be able to enter either list, Cancel, and see the other one.

**Steps to reproduce**
1. New character flow
2. Select the Player's Guide as a source
3. Fill in any details until the Upbringing page
4. Select the Alternate Upbringing toggle
5. Select the normal list, observe the list is correct
6. Cancel
7. Select the alternate list, also correct
8. Cancel
9. Select the normal list again, observe the list is still the alternate list

**Device**
Firefox 109.0.1 (64-bit), Windows 10

**Comment by Felderburg** [comment]
I noticed this too! I thought maybe it was an issue with the Vorta I was creating, and hadn't tested beyond seeing it on the one character.

**Comment by bcholmes** [comment]
Thanks for the report. Absolutely excellent job documenting steps to reproduce!
