### ISSUE TITLE
Ktarian supporting characters

### ISSUE THREAD

**Issue by bcholmes** [bcholmes/StarTrek2d20#14]
Ktarians are unusual in that they have 2 fixed species attribute improvements, and 2 from which the player must pick. It doesn't look like the supporting character tool implements this correctly.

**Comment by bcholmes** [comment]
Resolved.

**Comment by Felderburg** [comment]
The solution allows users to choose from all 4 remaining attributes, rather than limiting to fitness or presence. This may be a result of how the tool works, but I thought it worth noting.

**Comment by bcholmes** [comment]
Oh, good point.
