### ISSUE TITLE
Random Major NPCs have wrong primary discipline

### ISSUE THREAD

**Issue by CraftyAF** [bcholmes/StarTrek2d20#145]
When using the random NPC feature to create Major NPCs, the NPC is always created with the wrong discipline distribution. I.e. A security officer with security focuses and security talents but a 1 in the security discipline. This appears to be a minor bug since the Notable NPCs always end up with the correct distribution. I.e. A security officer with a security discipline of 3.

To replicate, simply roll any **Major** NPC and compare the Department field with the most relevant Discipline stat. E.g. Security officer - Security Discipline, Science Technician - Science Discipline, Counselor - Medicine Discipline, etc...

**Comment by bcholmes** [comment]
Well that's embarrassing. I've put a fix in place.
