### ISSUE TITLE
Sky blue in Monster Maroon colors

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#159]
Per https://memory-alpha.fandom.com/wiki/Starfleet_uniform_(late_2270s-2350s)#Department_colors (and Robert Fletcher's original notes) "sky blue" should be present as a division color.

(Note that Memory Alpha also has "purple", but it's not clear even in that article if it's intended to be an actual division color or if it's part of the field uniforms, and I think it can be left out.)

(Searching "robert fletcher monster maroon notes" brings up a facebook page as a top result that has them. I don't want to link to facebook, but it was the only source I could find. "View Full Size" brings up pages that can be downloaded.)

**Comment by bcholmes** [comment]
Huh. I'd seen a few references to the "Special Services" sky blue, but kept trying to find a canonical example of it -- I swear I searched Memory Alpha multiple times and was never able to get a match. So, not being able to verify it, I skipped over it. Thanks for the pointers.

**Comment by Felderburg** [comment]
I looked at some screencaps of the movies at Trekcore, there are a few more examples (that I remember seeing months ago, good lluck if you look again :p ). It's *extremely* rare. The original notes have it listed for commisary, janitorial personnel, special crafts (barbers, shoemakers, tailors, etc.... (explains why the Enterprise D's barber was a Bolian I suppose)), and recreation.

The notes get real nitty-gritty into details. White isn't just command, but also accountants and logistics and several other things.

Then again, the notes have some things that aren't seen on screen as well, but it is cool to read.
