### ISSUE TITLE
Ferengi and Changeling species duplicates

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#17]
When selecting all books (or I assume DS9 character and Alpha/Gamma quadrant books) the Ferengi and Changeling species are duplicated in the list. They are, I suppose, technically different, but it is a bit odd to see them that way. Not sure what the solution might be, especially since Changeling has different attribute bonuses depending on the book (although that is perhaps fitting).

**Comment by bcholmes** [comment]
You're right in that I think that there shouldn't be duplicates. I'll look in to a fix.

**Comment by bcholmes** [comment]
Resolved in latest build.
