### ISSUE TITLE
Character creator flow for Captain's Log cannot be completed

### ISSUE THREAD

**Issue by mer0mingian** [bcholmes/StarTrek2d20#173]
![image](https://github.com/bcholmes/StarTrek2d20/assets/16685125/14b2bf2e-a87b-48f0-95c6-b3d8aea54dc5)

In the last step of character creation I cannot select 3 Disciplines to increase, but upon clicking "Next" button am prompted that this is necessary to continue.

**Comment by bcholmes** [comment]
I think the latest push should have fixed this issue. Thanks for reporting it.

**Comment by mer0mingian** [comment]
Cool, thanks for fixing it so quickly. :)
