### ISSUE TITLE
Character Creation - Education Page - Unable to select secondary disciplines

### ISSUE THREAD

**Issue by Phantomaoj** [bcholmes/StarTrek2d20#183]
I am unable to complete a character beyond reaching the Education selection.  This is under the Standard RPG Rules. I select my 3 attributes, my primary Discipline but cannot select anything for the Secondary Discipline.  I field out the values and Focus and selected a Talent, then tried the Secondary Discipline and still nothing.  I tried to click next, received the message "Please select two secondary disciplines" and still I can not click the box to add anything.  This occurred on all of the Tracks.

I turned off Adblock, added the site as a whitelist to Adblock as well and it didn't help.
I restarted my PC, tried to make a character and receive the same issue.
I tried a different browser (Edge) and the same thing happened.

I am on Windows 11, running Chrome Version 120.0.6099.129 (Official Build) (64-bit). 
Everything was working fine on 12/17/23 (the last time I build a character).

Update: I attempted to use the "Solo RPG using the Captain's Log Rules" and had the same issue at the same spot on the Education regardless of what Track i tried.

Update 2: I tried it on a different PC (Windows 10; same version of Chrome) that had never used the builder before and ran into the same problem on Education section selecting the two Secondary Disciplines.
Thanks!

**Comment by bcholmes** [comment]
Whoops! That's a bug. Thanks for reporting it. I'll get a fix out in the hour.

**Comment by Phantomaoj** [comment]
Thank you for the quick response! 
The site is amazing, thank you for all of the work!
Merry Christmas!!
    On Sunday, December 24, 2023 at 06:40:17 PM EST, BC Holmes ***@***.***> wrote:  
 
 


Closed #183 as completed.
