### ISSUE TITLE
Black screen with only Continuing Mission and core selected

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#184]
When I only have CM selected as the extra book, and I click 'main character' in the step to choose what I'm creating, I get a black screen. I didn't do full testing to see under what conditions it replicates, but as far as I can tell, it only happens when just the Core and CM are selected, and no other books.

**Comment by bcholmes** [comment]
Good catch. If you don't have either the Klingon book or the Player's Guide, the "type of character" screen is skipped, and there's some essential set-up that happens on that screen. I'll get a fix today.
