### ISSUE TITLE
Species Randomization: Species available from unchosen books

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#187]
The new dropdown is great! In testing it, I tried it by unselecting captain's log and the non-delta quadrant books; and then another time by clicking the 'none' selection button. Both times, the dropdown still showed all selections, and even brought up species like Edosians, which should certainly not have been available with just the core book selected.

Edit: I guess it might be worth mentioning that the second time I tried this, I had a blue screen of death, but I strongly suspect it was unrelated as that has not occured again, and restarting initially gave me some boot errors.

**Comment by bcholmes** [comment]
D'oh! You're right.
