### ISSUE TITLE
Custom Race Homeworld

### ISSUE THREAD

**Issue by KingKrath** [bcholmes/StarTrek2d20#189]
Whenever I use the custom race option and go through to the Environment section, clicking homeworld, it goes to a black screen and won't let me proceed.

**Comment by bcholmes** [comment]
Definitely a bug. Should be fixed, now. Thanks for reporting it!

**Comment by KingKrath** [comment]
Thank you!
Sent from my iPhone

On Feb 9, 2024, at 09:39, BC Holmes ***@***.***> wrote:

﻿

Definitely a bug. Should be fixed, now. Thanks for reporting it!
