### ISSUE TITLE
App Not Working

### ISSUE THREAD

**Issue by TakeshiYamato01** [bcholmes/StarTrek2d20#192]
I just tried getting on the App, with both Firefox and Google Chrome (my primary browsers) on my PC.

It did not work.

On Firefox, I get this error message:

> The page isn’t redirecting properly
> An error occurred during a connection to sta.bcholmes.org.
>     This problem can sometimes be caused by disabling or refusing to accept cookies.

Meanwhile, on Google Chrome I got this:

> This page isn’t working
> sta.bcholmes.org redirected you too many times.
> Try deleting your cookies.
> ERR_TOO_MANY_REDIRECTS

Is the app down or something?

**Comment by kaktoforum** [comment]
Found out this issue yesterday.
Same for sta. and blog. subdomains.

**Comment by kaktoforum** [comment]
~~As a temporary solution, started server on http://sta.world-jct.net/
Will go down after main server starts working.~~
Prod is up, turned off my server.

**Comment by bcholmes** [comment]
Sorry about that, folks. Should be resolved, now.
