### ISSUE TITLE
Support Cyrillic Characters in PDFs

### ISSUE THREAD

**Issue by bcholmes** [bcholmes/StarTrek2d20#195]
The base PDF specification uses a version of the Helvetica font which does not really support Cyrillic characters (it has other langauge limitations as well). When you try to export the a character as a PDF, the export fails because the PDF cannot be properly saved.

The PDF library that the app uses ([Hopding/pdf-lib](https://github.com/Hopding/pdf-lib)) has some functions relating to changing the font, but to date, I've note been able to successfully export a PDF with Cyrillic characters in it.

Here are some relevant links:

- https://github.com/Hopding/pdf-lib/issues/548
- https://github.com/Hopding/pdf-lib/issues/1528
- https://github.com/Hopding/pdf-lib/issues/1570
- https://github.com/Hopding/pdf-lib/issues/1152

**Comment by bcholmes** [comment]
PR #196 seems like a fix for this bug.

**Comment by LoranRendel** [comment]
> PR #196 seems like a fix for this bug.

It's now a partial fix for Russian TNG only, we can replace font for every card type to get Cyrillic support in each sheet type.
