### ISSUE TITLE
JSON file to import into Roll20

### ISSUE THREAD

**Issue by Detaaz** [bcholmes/StarTrek2d20#208]
Hey the website is a great resource but I was looking for a way to import the files directly to Roll20. I see on the website, #119 and #120 that there is support for VTTs and was wondering if Roll20 was possible/likely?

**Comment by bcholmes** [comment]
Yeah, it's definitely a thing I intended to support; I just haven't gotten around to it. 

Could you export a character and attach one to this ticket? That'll help give me a first look at what's needed.

**Comment by Detaaz** [comment]
Yeah no problem. I can also do the same for NPCs and Ships if it helps.

[Lenara Ral (she_her).json](https://github.com/bcholmes/StarTrek2d20/files/14921990/Lenara.Ral.she_her.json)

**Comment by bcholmes** [comment]
How do you import/export the JSON to Roll20. I'm honestly not seeing the ability. (I've just snagged a pro membership and bought the STA book; I just can't find the import/export feature).

**Comment by Detaaz** [comment]
Sorry that's completely my fault. It's done via a browser extension called VTT Enhancement Suite found [here](https://justas-d.github.io/roll20-enhancement-suite/index.html). Had it installed for so long I blanked that it was even an extension. With that installed there's an import button on the Journals tab once you've launched a game.

**Comment by bcholmes** [comment]
I've put an initial implementation on the server. At the moment, it only works with characters (and only supporting Main character sheets), not starships. Give it a spin, and let me know how it works for you.

**Comment by Detaaz** [comment]
Seems to work perfectly for both

**Comment by bcholmes** [comment]
Since I now support starships as well as characters, I'm going to mark this as done.
