### ISSUE TITLE
Starship VTT export for Roll20

### ISSUE THREAD

**Issue by TamReese** [bcholmes/StarTrek2d20#216]
The Export button for Starship VTT is greyed out.  Forgive me if I missed something already posted regarding this, but is there a workaround? Thank you!

**Comment by bcholmes** [comment]
Starships weren't originally supported for Roll20. I've thrown in some preliminary support, now.

**Comment by bcholmes** [comment]
Okay, I finally figured out how to show Starship sheets, rather than just handouts. The latest build should provide better support for this requirement.

**Comment by TamReese** [comment]
That's amazing. Thank you!
    On Friday, June 7, 2024 at 08:29:25 PM EDT, BC Holmes ***@***.***> wrote:  
 
 


Okay, I finally figured out how to show Starship sheets, rather than just handouts. The latest build should provide better support for this requirement.
