### ISSUE TITLE
Just wanted to report

### ISSUE THREAD

**Issue by KeptinJurk** [bcholmes/StarTrek2d20#222]
energy weapons on the ship creator are not being adjusted.

E.G

I made a battlecruiser excelsior, 2 refits.

so scale 5, security 3. which means phasers are 8 Dmg.
and since it has phaser banks, +1 for 9.

but the ship sheet the ship creator makes says '4' dmg. which is a whopping 5 damage die off.

so i just wanted to let you know some parts of the starship creator are not talking to each other in your coding.

NOT COMPLAINING or bitching. just wanted to let you know is all.

starship sheet also does not seem to have power on it.
(engines 9 + secondary reactors + 5 = 14 power)

**Comment by bcholmes** [comment]
I assume that you're referencing the new 2nd-edition-esque Starship sheet. It looks like I made a mistake on that one. Should be fixed now.
