### ISSUE TITLE
Quick First Pass Errors a Character Creator (Main Characters using 2e only tab option) Part 1

### ISSUE THREAD

**Issue by MasterofMankind** [bcholmes/StarTrek2d20#223]
First noted by me (ImperialOne-STOChili) to you in Discord, but reproduced here for your reference:

1-Resolute (human trait in Core2e pg 152) states Stress has Command value added to it. In the app, the number 3 is added instead (which is what was defined in Core1e).

2- in the app's Character sheet, hitting the Export to PDF tab in all cases leads to... nothing. No action is executed. There is no generation of pdf that is downloaded anywhere (i.e. to Downloads file). Incidentally, Export to VTT does correctly download a file to the Downloads file.

3- The description for the Veteran talent is incorrect. Per Core2e pp128, Veteran talent has player roll a singled20 after Determination is used. A roll equal to or less than the character's Control allows the Determination to be recovered. Since D6/Vhallege dice eliminated in 2e, all d6 type rolls from Core1e are now gone.

4- Damage for weapons on the app is calculated incorrectly. As an example, a Phaser type-2 previously is 4+ Security. Damage is now Severity and Fixed, a Phaser type-2 is now a Severity 4. THe char sheet in app does the calculation as weapons (Core1e) damage plus character's Security score

**Comment by bcholmes** [comment]
I haven't seen #2 happen. Can you share the View URL for the character that manifests this behaviour, and let me know which sheet you were trying to use?

**Comment by MasterofMankind** [comment]
[CharacterPlay1]([Captain Charles C. Li - STAR TREK ADVENTURES (bcholmes.org)](https://sta.bcholmes.org/view?s=eJyNVF1v0zAU_SuWH-AlGxsSX32r0ooCG1RrgQe0B8-5SawldmQ7hWj0v3NumzZZ1Qe0Pqy31-crx3mSIZInF7uG5ETWyti0VF5pTGUi-_EqKp9XRBEj8gqTr_QnfiSLL9E4i7FVNW_y4YqCSC_FjcF4Qz7wwuQ6kW3z4I0t8JGTJ2kyBtaGrKapzdakS-sqV3Q4pbSmJhI2om8pkbnTbcD6EmitCnvGzARtmspYGoBYsqrIRmboJa2oyi_uqDIK4-02kVp5gjtsYLOIJXZ-EPwqRt2oquVTP0mkriZhrFiSOo98ODWAzjfYgNJfe39vBunz0EC2KhhIxejNQxsZY6Y4k1M7oK6VzeQ22QO9vhqQFvhBLEsVEMYJ2NJT6GM4D3efSAh-HHlIVRPx0HGCea7gJDSEMAPvNN7UyndM2ta7eEJUO3-AtNG7CqOjg082mKKM8v5MVHcUXMUiOavowdjXAP_rx5HE3iftSGZw4GqluRPzmnwBc524pcxoNpagmCggFZ14IdborNGB2XvZs3MRjALbU5yqT4YU78cx7rbH1KRbb2LHW4fSrEsSczydz22IJkeIImJyS8qGc_2ZUU5g3ZBY94lMxJ2yBYp_iGkf9vH-iW95bjTKC1KyG-OdrXvM3X1aoLK_na-yk2IMT-v5rTl4GCwsVNOYqhNoshfTnF8DkJJDXSiZ5nl6_xXaiOWY3yg01oa3iTBB5M6LL4ghMCfflYmcZm3F-CqAyVK2Kk3D7580vfhw_f7tO_FXfL9c4U-sX6aL6c3NVHIBnHWt5dtS0qvS1JjBPh1z6tsAqkOg2-0_QwSyLw))

With further testing, hitting Export to Pdf does generate a file into Downloads folder EXCEPT for the case of the default TNG Portrait Character Sheet (US-Letter) format... pressing Export to Pdf literally does nothing in the above link.


I just made a version 2 of same character (I got Deadeye Marksman as a trait, this is from PlayersGuide, I thought I just had the Core2e tab only selected) and the 

[Version2Character](https://sta.bcholmes.org/view?s=eJyNVE1z0zAQ_SsaHeDilrYHoLllnAwBWsg0AQ5MD6q8tjW1JY8kBzwl_523iRO7JQcmOSTr1fvatZ5kiOTJxa4hOZG1MjYtlVcaVZnIvryKyucVUUSJvELlC_2OH8jiTzTOomxVzZ18uKIg0nNxY8TmCk825AP3TC4T2TYP3tgCXzl5kiZjbG3IaprabE26tK5yRYdTSmtqIqEj-pYSmTvdBrQvgdaqsCfNTNCmqYylAYhVq4psZIZe1Yqq_OyOKqNQ3m4TqZUnGEQHOotYouc7wbJi1I2qWj71g0TqahLGiiWp08iHUwPofIMOKP2593d1MWifhwa6VcFIKkZvHtrIIEtPoZf-zBHYa2UzuU32WNfXA9YCD8SyVAF5vICbKc74n3hIt97ETm7vEwnJjyMXqWoiJo8jTHMBL6EhxBm4p_GmVr5jzrbeBRSi2jmEQBu9q1A6cn60wRRllPcnwrqj4CrWyGlFD8Z-EfBbP44M9zZpRzKDBVcrzVsxr8kXiKoTt5QZzc4SbCe2kIpOvBJrLK7Rgdl72bNTgY7y2lMc1I8mMTIy5LjrHlMfQr0f1mZdkphjOJ_aEE2OEEVE5ZaUDac2aEYqow4Nyj-Gul8lDmcf8fHVE1_z3GgsLajIbox3tu6Rdu_RAqv6y_kqe7ENw4xOr8MgfKGaxlSdwAZ7Mc35BoCUHFMKJdM8z-y_ohoCP4Y2Soql4R4RJojcefEZMwhMyW_IRE6ztuILRwWgW8pWpWn45knTs-vL92_fiT_i2_kKH7F-nS6mNzdTyVN31rWW35CS3pSmRg3u6RhTrwhUhzy3278GgK-f) 

still does not Export the default TNG Portrait Character SHeet (US-Letter) format to the Downloads folder

**Comment by bcholmes** [comment]
Okay. Thanks for posting that. I can see the "Export to PDF" error, but it looks like the error only appears on version 1 characters. I'll push a fix soon.

The second character you've posted is also a version 1 character: I'm not sure how you've ended up there if you had the "Core 2e" source selected, but the view page does not show the species ability (a human should have one), the lower stat block says "Disciplines", rather than "Departments". There's also no "Pastimes" section.

**Comment by MasterofMankind** [comment]
I think I might know what I did wrong... at this point, on the very first screen when selecting Core 2e, the original Core remains selected. This is meant to be (cuz I cannot seem to unselect the regular Core tab above the Core 2e)?

I can now generate this... [Version4Character-Core2eV1](https://sta.bcholmes.org/view?s=eJytVMtu2zAQ_BWCh_biPIG-fDMUo26btEHstofAB4ZaSUQoUiApt0Lqf--sLD8SuLfCPtjL5ezMcMgnGRMF8qlrSI5lrYzLKhWURlWO5FCeJxUKS5RQoqBQ-Uq_00dy-JOMdyg7VXMnb7YURXYqro3IfKBLsbrA-opC5M7x5Ui2zUMwrsRXjp-kyXmCNuQ0TVy-IF05b33ZYZfSmppE6EihpZEsvG4j2m-B1qq4GZ2bqE1jjaM9EHNXllziCQO3O4retonkej2SWgWCRKyiq0wV1n8QRCtGXCnb8o6fBAk1CePELanjqNtdDNqomAxX72XmrSWdovB5LuqOXTYUzyLpQCnK5ZbBdAU4SLrfGHF5vhc5jQ0EqpLHqpSCeWDyEB8oDhqfSQfVWrlcrkcbrDd7qBnq4rZSEb69QLtSfBb_xAJRqHs8EJypJiEm2MFDziE7NgTXI_c0wdQqdDyyrXsvY1K9PkC6FLxFaTfyk4umrJJcAiQFgA6RwG_9eMBiEEI9zhVI-lppzse0plDCi07cUG40cx8hrUgllZ14JRYIstG93QOzq2MqDxzZjHhJcLQ3fXnoVN89J90Gk5jPjsVyH6JFRWIK-z-3CEcBn0RC5YaUi8fyNCdbnNyRNQrl9WDMxsHdNRTfisJoxBdjyK1M8K4eUPrbNENof_lg8xdnvT-C53dmL2BLeqaaxthOIJ5BTAp-DUClwAnFisc89-t_2MTc8KgIE0Xhg_iCAzjuTyKVd4ITHXt_-IKM5SRvLRNQEVQc5fPKNPxOZdnJh4v3b9-JP-L76RwfsXidzSbX1xPJmfDOt45vSEVnlalRgz-0M3IICLhsHV-v_wIUW8AA)         and everything saves to Download folder.


On the character sheet... the Phaser type-2 still incorrectly lists 7 for damage (1e calculation) instead of the fixed Severity 4 in Core2

In addition, I uncovered instances of a typo, but there may be more as they all fall into same category of "errant hyphenation." 

Under Talents:
1- Computer Expertise (Science): Whenever you attempt a task that involves the program- ming or study of a computer system, the first bonus d20 you purchase is free.

2- Constantly Watching (General): At the start of an action scene, the gamemaster must spend an additional 2 Threat to have an NPC take the first turn. You may also re-roll 1d20 on any task attempt- ed to locate a hidden enemy or danger.

3- Gut Feeling (General): When the gamemaster spends Threat to introduce re- inforcements or to cause a Reversal, they must spend 2 additional Threat to do so. This is 2 extra Threat in total, not per reinforcement.

4- Personal Effects [Rank: 1] (General): You possess some significant and uncommon item or device which is not standard issue, but which is never- theless useful for missions. You may select this talent multiple times, gaining a different item each time.

5- Positive Reinforcement (Medicine):  Once per mission, you may attempt a Presence + Medicine task with a Difficulty of 3, while providing emo- tional or mental treatment for another character. Success creates a character trait for your patient that lasts until the end of the mission: Boosted Confidence. In addition to the normal effects of the trait, that character can reroll their dice pool, as if they’d spent Determination, once be- fore the end of the mission. If the task the character used their reroll on fails, they lose the trait created by this talent.

6- Quick Study (Medicine): When attempting a task that will involve an unfamiliar practice, technique, or medical procedure, or which is to treat an unfamiliar species, ignore any Difficulty or compli- cation range increase stemming from your unfamiliarity.

7- Stimulant Shot (Medicine): When you perform the First Aid task to revive a Defeated ally, you may add 1 Threat to let that ally recover Stress equal to your Medicine rating. A character may only bene- fit from this talent once per adventure.

8- Testing a Theory (Science): When you attempt a task using Engineering or Science, the first bonus d20 you purchase is free, so long as you succeeded at a previous task covering the same scientif- ic or technological field earlier in the same adventure. If you created a trait that represents a hypothesis about an unknown phenomenon, you may also re-roll one d20 on tasks related to that hypothesis.

and formatting issues under the explanations of these Talents:
1- Close-Knit Crew (General)
2- Studious (General)
3- Technical Expertise (General)

**Comment by MasterofMankind** [comment]
Thanks. I posted a reply, but I think I may have used wrong tabs? Now, I stay with Select None, add the Core 2 tab… and notice the Core tab above it can not be unchosen.  Is that always the case?

Charles

On Aug 22, 2024, at 5:57 PM, BC Holmes ***@***.***> wrote:

﻿

Okay. Thanks for posting that. I can see the "Export to PDF" error, but it looks like the error only appears on version 1 characters. I'll push a fix soon.

The second character you've posted is also a version 1 character: I'm not sure how you've ended up there if you had the "Core 2e" source selected, but the view page does not show the species ability (a human should have one), the lower stat block says "Disciplines", rather than "Departments". There's also no "Pastimes" section.

**Comment by bcholmes** [comment]
Thanks for such a thorough copy-edit on those talent descriptions. I think I've resolved items 1, 2, and 3. Representation of weapons still needs a bit of attention.
