### ISSUE TITLE
Talent list sorting oddity

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#23]
The talents that begin with "I'm" sort differently depending on whether the apostrophe is a straight quote mark vs a curved one (I think this only applies to "I'm a Doctor..." and "I’m Giving It All She’s Got!" (note the different punctuations in my copy/paste).

("I'm giving it" also says ops division, not player's guide, but I think that's covered in #22  )

**Comment by Felderburg** [comment]
(It may be worth noting that I'm doing my own thing with talents, which is why I've been so nit-picky about them as I notice them in your app).

**Comment by bcholmes** [comment]
Nit-picky is helpful.

**Comment by Felderburg** [comment]
So apparently the straight quote vs. curly quote sorting is an issue that happens in Excel as well, so it must be how they're sorted in whatever system (unicode?). After looking into what the deal is, I would prefer curly quotes, as that's the preferred way to denote printed apostrophes (as opposed to straight, which in print denotes things like 'prime'), it's how they appear in the books, and the only reason this is an issue is because typewriter manufacturers wanted to save space by combining similar-looking keys.

**Comment by bcholmes** [comment]
Doing this change make clear to me that mixing standard apostrophe's with the curly single quotation mark makes the filter less predictable. I think most people are going to type a standard apostrophe, which in the original code, would fail to match a name that had a curly quotation mark in it.
