### ISSUE TITLE
The Starship creator gave me a runabout that uses d6/starfleet delta dices instead of the 2e damage rating 

### ISSUE THREAD

**Issue by GoatQueerEnjoysChocolate** [bcholmes/StarTrek2d20#237]
So, I'm creating a Runabout from the year 2600 that uses Chroniton Torpedoes and Graviton Beams, but for some reason it gave me d6 dices for the damage rating instead of the damage rating of second edition. Is this like a bug or something? 
![image](https://github.com/user-attachments/assets/afbd3402-bef0-4d0e-91dc-963f7b22a1d0)

**Comment by bcholmes** [comment]
You're right. That's a bug. Good catch!

**Comment by bcholmes** [comment]
Should be fixed, now.
