### ISSUE TITLE
Unarmed Strike challenge dice value too high? [1e]

### ISSUE THREAD

**Issue by woolfben1** [bcholmes/StarTrek2d20#239]
First time GM for STA, and one of my players found this awesome tool of yours, thanks for creating it!

Whilst working on characters sheets for some of the players and NPCs in my game, I noticed that the Unarmed Strike consistently appears to have one extra Challenge Dice compared to the NPC listings in the book, or when I figure things out manually. The book and [this Reddit post](https://www.reddit.com/r/startrekadventures/comments/f9gq0o/damage_rating_calculation_for_unarmed_strike/) puts it as 1 + Security. Ranged weapon attacks appear to be correct, so I think the unarmed "weapon" values are a point too high.

**Comment by bcholmes** [comment]
You're right. It looks like this got messed up during the conversion to 2nd edition.
