### ISSUE TITLE
Starbase inclusion?

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#29]
Page 95 of the command book includes Starbase talents. Now, it's perhaps not that useful to include them for creating a ship, but it may be nice to have them included in the overview list.

Although I suppose it may be possible to expand the starship creation to allow for starbases as well, given that they are essentially the same process.

**Comment by bcholmes** [comment]
Starbase talents were added to the list of talents with 16974cd2870feee41eef3e8dc6c424a1a0925569.
