### ISSUE TITLE
Final page wording/new user finding final stats

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#32]
The last page of the creator says "Your character is finished. You can either use this reference to fill in a character sheet by hand, or use the button at the bottom to export your character to PDF."

However, the "this reference" requires clicking on the "profile" button to actually see stats, if filling in by hand was desired. I can see a situation where a user doesn't necessarily know that, and is perhaps less inclined to click around and find out what things do, which would leave them wondering where the actual stats are.

Perhaps referencing the button would be useful? (Not sure putting the stats on that page is a good idea, as it's already reasonably full.)

**Comment by bcholmes** [comment]
Resolved.
