### ISSUE TITLE
Stat sheet storage/recall

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#33]
Per the modiphius thread, work has already begun on a way to "store" or "recall" a character or ship sheet with a "unique" url. I figure it should be an actual item here, for further brainstorming etc.

Is it a unique url per sheet, or is it something like a url that has a "code"? In other words, does character A get sta.bcholmes/CharA and character B get sta..../CharB? Or is it more like "characters A and B both have the same stats, so they each get sta...../Pres1_Insight2_Conn3 (etc.)"?

**Comment by bcholmes** [comment]
The URL embeds all of the information about the character -- stats, names, lifepath options, etc. If two characters are identical in all respects, they'd get the same URL. That also means that a URL is a "point in time" representation of a character. If I later give folks the ability to alter a character, the altered character would necessarily have a different URL.

**Comment by bcholmes** [comment]
I've implemented this concept for Starships and Supporting Characters. I'll leave this Issue open until I finish it for main characters.

**Comment by bcholmes** [comment]
Main character support now exists. All character types as well as star ships can be bookmarked.
