### ISSUE TITLE
Add a tool to generate Shackleton Expanse planetary systems

### ISSUE THREAD

**Issue by bcholmes** [bcholmes/StarTrek2d20#35]
There have been a [couple of](https://forums.modiphius.com/t/star-system-generation/17513/9) [threads](https://forums.modiphius.com/t/hex-crawling-the-shackleton-expanse/17264/8) on the Modiphius forums about the rules from the _Shackleton Expanse_ book for generating planetary systems and "hex-crawling" the Shackleton Expanse. 

I'd like to add these capabilities to the character generator, 'cause I like planetary systems. Forum user Mister X mentioned having some Python scripts that can produce some interesting output.

**Comment by bcholmes** [comment]
Although the rules are specifically about the Shackleton Expanse area of space, obviously people may want to have planetary system data for other areas of space.

**Comment by Felderburg** [comment]
There's also the potential for other generators. For example, the biohazard options in the sciences division, or including the red/blue/gold plot component tables from the division books.

Anyways, the first post you link seems to include all the resources I found for creating planetary things, as well as a good method for doing so. It seems like it's just a series of dice rolls, so it could be as easy (for the user) as a single button push to generate a sector of space.

**Comment by bcholmes** [comment]
Here's a system map I created for one of my STA campaigns:

![mariah_system](https://user-images.githubusercontent.com/2981347/160249400-20705b1c-3393-4017-82b7-81f184c32818.png)

I'd like to be able to auto-generate something like that. When I made the map, I put the orbits on a logarithmic scale, so they look "closer together" than reality; it helps use the available space a bit more effectively.

**Comment by Felderburg** [comment]
That seems exceptionally ambitious, but very cool. Are images something the tool is able to do?

I wonder if just having a list is sufficient, not only for a first start before incorporating auto-generated images, but also for people who might want to make their own art, or want era-specific art that isn't yet an option. Or even people who just like database-type things.
