### ISSUE TITLE
Project Escalante

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#47]
Per Modiphius user [LucasCunnigham](https://forums.modiphius.com/t/star-trek-adventures-online-character-generator/94/335?u=felderburg), there is an additional space frame on page 108 of These are the Voyages Vol. 1. I agree with Sutehep's suggestion that it should be named Project Escalante.

As for whether it should be included, given that it seems adventure-specific... I say add it! It's an official spaceframe, and is a cool concept generally. It would certainly be workable into other campaigns/adventures.

**Comment by bcholmes** [comment]
Resolved in latest build.
