### ISSUE TITLE
Source selection: "Core" button oddity

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#48]
I'm not sure if this is a bug, but it seems odd to me. When I select most books (sources), clicking multiple times will just select or unselect that book. But when I click the Core button, the result is different.

If nothing is selected, nothing happens. If one or more things are selected, clicking the Core button multiple times will deselect them, in reverse order of how they were selected until only Core is selected.

I understand that at least one book needs to be selected, but I wonder if requiring one of the two (three? if tricorder counts) core books to be selected (with an error message if not) is sufficient. It just seems very odd to me that clicking the Core button affects other book buttons (at all, and especially in the manner described).

**Comment by bcholmes** [comment]
Resolved in latest build.
