### ISSUE TITLE
Cadets

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#49]
Per comments on [modiphius forums](https://forums.modiphius.com/t/star-trek-adventures-online-character-generator/94/347), cadets are an odd thing. Just making this an actual "issue" so it can be addressed here/notes or discussion about its technical aspects can be kept on github.

**Comment by Felderburg** [comment]
As noted on the forums, "cadet" is a rank, not a role. Cadets go through step 5 (or 6 for higher-level cadets) of lifepath creation. The remaining points are meant to be granted in game, when the character becomes what they would be as if a "young officer" was rolled up at creation.

So it seems like a cadet would have an option at step to be an upper-level cadet, and get that single career event if wanted, before being taken to the end screen.


...

I wonder if cadets are an ideal testbed for modifying characters after the fact... or maybe their special case would make it weird? But it does seem like allowing a person to come back in and add step 6, and then step 7, might be useful for cadets.

**Comment by bcholmes** [comment]
Cadet support added.
