### ISSUE TITLE
Suggestion: Group Books/Sources

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#51]
Well, the good news is that Modiphius continues to release loads of stuff. But now the source selection page feels... cluttered to me. This may be entirely a matter of opinion, but I think the books should perhaps now be grouped by type (division, quadrant, sourcebook, campaign guide?).

If you wanted to get really fancy, a button that allows for a dropdown to choose each type's individual books, or a toggle button for all books of a certain type.

**Comment by bcholmes** [comment]
Part of the current build.
