### ISSUE TITLE
Black screen after selecting "allow any species" under the Klingon Defense Force

### ISSUE THREAD

**Issue by DjZekrom** [bcholmes/StarTrek2d20#63]
Heyo! So I'm trying to make a character for the Klingon Defense Force that isn't Klingon using the Klingon core rulebook. After selecting the "allow any species" option on the select species page, the site goes completely black and is unusable. After refreshing the page it will take me back to the beginning and I'll lose all my progress. I have not found a way around this issue and I would be very grateful if it could be fixed.

Edit: I don't know how to label this issue as a bug but I believe its a bug

**Comment by bcholmes** [comment]
Okay. I think I found the culprit. Try it now.

**Comment by DjZekrom** [comment]
it works! thank you!
