### ISSUE TITLE
Suggestion: Small Craft

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#71]
It would be nice to have small craft included in the creator. For some small craft, it might be too much of a copy/paste from the source books, but things like a runabout with its modules would be something nice to include. And the build-a-frame in UP apparently includes small craft (per the [UP forum post](https://forums.modiphius.com/t/utopia-planitia/18449/48)) so it seems like the UP revamp of the tool would be a good time to add them.

**Comment by TakeshiYamato01** [comment]
I have access to the PDF of the book (I preordered it from their site, still waiting for them to ship the hardcopy). And I can state that yes, it DOES have rules for the development of small craft, as well as space stations. It would probably be a good idea to add those to the app, too.

**Comment by bcholmes** [comment]
Small craft are now supported.
