### ISSUE TITLE
Visual Spectrum talent not appearing

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#72]
Per the [Modiphius post](https://forums.modiphius.com/t/star-trek-adventures-online-character-generator/94/370?u=felderburg), Visual Spectrum isn't showing up when Efrosian is selected as race, despite appearing in the main page talent list as an Efrosian talent. In fact, it isn't showing up even when 'allow cross-species talents' is selected.

Edit: I looked at the talents list, it appears that this talent not appearing when 'allow cross-species' is selected is intended, if I'm reading [helpers/talents.ts](../blob/master/WebTools/src/helpers/talents.ts) correctly.

**Comment by bcholmes** [comment]
Fix was committed with 16974cd2870feee41eef3e8dc6c424a1a0925569. It is now pushed to the server.
