### ISSUE TITLE
Support Unofficial sources of character sheets, Talents and ships

### ISSUE THREAD

**Issue by bcholmes** [bcholmes/StarTrek2d20#8]
As proposed by ninjew42 on the [Modiphius Forums](https://forums.modiphius.com/t/star-trek-adventures-online-character-generator/94/243?u=bcholmes):

> Adding in various fan character sheet types like the Romulan one that’s out there and talents made by the Continuing Mission group, could include a source button for Continuing Mission resources.
> 
> I know for some species there doesn’t seem to be anything so far that suggests we’ll get talents for Jem’Hadar or Vorta for example so having the fan work added could be helpful for people wanting to make those kinds of characters so they don’t have to go back and modify the sheet after.

**Comment by Felderburg** [comment]
So it looks like some non-rules species have been added already (Borg, Gorn, Jem'Hadar, Reman, Romulan, Vorta). Where are they from? And what books are they tied to in the tool? For example, selecting core book only and TNG era, Gorn and Reman aren't available, but the others are, which seems odd.

**Comment by bcholmes** [comment]
Those were added before I started working on the code: I *think* they're reflections of the NPC write-ups in various characters. So, for example, there's a Reman bodyguard written up on p. 106 of the Beta Quadrant book (with an "Reman Character" info box).

**Comment by Felderburg** [comment]
Yeah, I found a few of them later. I suppose the question is whether they should be in the tool, given that they are "unofficial"... although they do use the Modiphius species wording and attributes, so it's a weird grey area. My suggestion would be to have an "unofficial" button added to the source selection (although it's already quite crowded).

**Comment by bcholmes** [comment]
I don't think they're "unofficial". I think the point is that you can make Major NPCs that happen to be Cardassian even if you only have the "Core" book. (Obviously, the "Starfleet Academy" lifepath option is a bit weird, then, but whatevs).

**Comment by bcholmes** [comment]
I now support Continuing Mission as an unofficial source. If another source with non-trivial usage emerges, I'll look in to supporting that, as well.
