### ISSUE TITLE
Suggestion: Klingon Great Houses

### ISSUE THREAD

**Issue by TakeshiYamato01** [bcholmes/StarTrek2d20#80]
So, the Klingon Empire Core Book includes the option for making Great Houses, and making characters from those Houses. The character creation part of that replaces the Environment and Caste steps of character creation.

Any chances we might get that functionality in the app?

**Comment by bcholmes** [comment]
This is the same as #26, so I'm going to close it as a duplicate.

Short answer: yeah, we want that function in the app, but I've been a bit slow to get around to it.
