### ISSUE TITLE
Changeling, Ferengi not available when only DS9 book selected

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#91]
Both Ferengi and Changelings should be available to people who select the DS9 book. Ferengi also appear to be missing the DS9 talents even when Gamma quadrant is selected.

Note: fix to issue #17 may be a culprit or a place to start.

[Side note: how did you determine which Changeling stats to use? The third attribute is different, and I vaguely recall you asking in a forum post somewhere, but I can't find it.]

**Comment by bcholmes** [comment]
Re: the first part of this. I'm not seeing that. When I select only the DS9 book (in addition to the Core), I see both Ferengi and Changeling available (although I suspect that you won't see them if you haven't chosen the Next Gen era).

Re: the second point: there are completely distinct species stats for the Ferengi-as-appears-in-DS9 book and Ferengi-as-appears-in-Alpha-Quadrant book (there's also a Ferengi-as-appears-in-Core). Those species write-ups have different Talent lists. There's a special bit of code that excludes the "older" Ferengi write-ups if a new one exists. Same is true of Changelings, Klingons, and one or two other species. All that logic kinda pre-dates my involvement in the app development.

**Comment by Felderburg** [comment]
Hm. Well now I'm seeing them. Maybe I didn't have the correct era chosen? Very weird.
