### ISSUE TITLE
Bug: Blank Fields on Klingon Ship Sheet

### ISSUE THREAD

**Issue by TakeshiYamato01** [bcholmes/StarTrek2d20#92]
I just made a couple of Klingon Starships using the App. Checking the PDFs afterward, I discovered that the fields for Name, Communications, and Total Power are blank. Further checking reveals that the values ARE there, and show if you click on the field as if to edit it, but those fields show as blank when not being edited.

**Comment by bcholmes** [comment]
This topic has [come up before](https://github.com/bcholmes/StarTrek2d20/discussions/13). It's unique to some PDF viewers (and I think it's only ever been raised on Windows). In that link I provided, user [jellial](https://github.com/jellial) mentioned a work-around that might work for you. 

Next time I fiddle with the Klingon Starship sheet, I'll look at the sizes for those fields.

**Comment by TakeshiYamato01** [comment]
Just tried the work-around, and they still don't show. I will mention I'm using Adobe Reader on Windows 10 OS.

**Comment by Felderburg** [comment]
I've just downloaded the examples in the linked #13. I have the issue with the character, not the ship. I'm using Acrobat (full version) and when I prepare the form and look at the number field properties, the appearance shows that the font size is set to 12pt, rather than "Auto" or a smaller font size. On the ship, the numbers are set to 10pt font. I don't know how the tool does its conversion to pdf, but that may have something to do with this issue.

(The number fields are also all slightly different sizes on the character sheet.)

**Comment by TakeshiYamato01** [comment]
Just made a new Klingon ship in the app as a test, and will attach it here for review.
[I.K.S. Mow'ga (Vor'cha-class) (Test).pdf](https://github.com/bcholmes/StarTrek2d20/files/9965430/I.K.S.Mow.ga.Vor.cha-class.Test.pdf)

**Comment by bcholmes** [comment]
I've tweaked the sheets a bit. Let me know if that helps at all. (I use a Mac, so I never see this problem manifest).

**Comment by TakeshiYamato01** [comment]
[I.K.S. L'Char (B'rel-class) (Test).pdf](https://github.com/bcholmes/StarTrek2d20/files/9976286/I.K.S.L.Char.B.rel-class.Test.pdf)

...If anything, it's made it worse. Even more fields are now unable to be seen unless being edited - including ALL the Systems and Department fields.

**Comment by TakeshiYamato01** [comment]
Also, just checked the TNG Starfleet ship sheet, and I can confirm that the problems are ONLY in the KDF Sheet.

**Comment by TakeshiYamato01** [comment]
...Scratch that - just built a TOS ship, and the TOS Ship Sheet has problems, too. Only the First Talent of the Talent List is visible, and Name, Service Date, Mission Profile, Spaceframe, and Refits are hidden. The TNG ship sheet is the only one I have seen that does _**NOT**_ have any problems.

[U.S.S. Hiryu (Nimitz-class) (Test).pdf](https://github.com/bcholmes/StarTrek2d20/files/9977760/U.S.S.Hiryu.Nimitz-class.Test.pdf)

**Comment by bcholmes** [comment]
I'm not gonna lie: trying to divine why it is that Acrobat Reader has a problem with something that the other PDF readers don't is not an easy task. The best I can try to do it determine differences between the PDF inputs to work around Acrobat's wonkiness.

**Comment by TakeshiYamato01** [comment]
Gotcha. Well, like I said, TNG ship sheet is working just fine, so you don't need to do anything with that one.

**Comment by bcholmes** [comment]
I've tried one more tweak on the file. Can you give that a try? (You may need to clear your cache or use a private window to ensure that your browser downloads the latest version).

**Comment by TakeshiYamato01** [comment]
I THINK THAT DID IT!!!

On the KDF ship sheet, at least - still need to try the TOS ship sheet

**Comment by TakeshiYamato01** [comment]
TOS ship sheet still has the problems I listed when I sent in that sample. TNG and KDF are both fine.

**Comment by bcholmes** [comment]
If you have a chance to retry the TOS sheet, I'd welcome hearing how that goes for you.

**Comment by TakeshiYamato01** [comment]
Looks like it works. All ship sheets are now working at 100%.

**Comment by TakeshiYamato01** [comment]
Umm... looks like the issue has returned, now occurring on the TNG sheet - updating it to include Special Rules Fields has rendered Communications, Engines, Structure, Crew Support, and Power blank. At least on Adobe, if I open it on Google Chrome it's fine, but I need to open it in Adobe if I want to edit it.

**Comment by bcholmes** [comment]
Hmm. That's frustrating. When I look at the field sizes for those fields, everything looks like it should be right. I've increased the sizes of some of those fields and I *think* that might have tweaked things. You might need to clear your cache to get the changed result.

**Comment by TakeshiYamato01** [comment]
I'll check it out - just refreshing seems to load in the updates for me.

**Comment by TakeshiYamato01** [comment]
Yep, it worked.

**Comment by TakeshiYamato01** [comment]
I hate having to keep bringing this issue up again and again... but it's happening again. This time with the TNG Starfleet Character Sheet. Made a Starfleet Supporting Character with the App, and the fields for Control, Fitness, and Presence are hidden on Adobe Reader when not being edited.

Please fix.
